# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id', 'name', 'time_server']},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['sensor', 'time', 'time_app', 'time_server']},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['device', 'custom_id', 'name', 'time_server']},
        ),
        migrations.AddField(
            model_name='log',
            name='custom_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='custom_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
