# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20160418_0540'),
        ('main_site', '0004_auto_20160418_0804'),
    ]

    operations = [
    ]
