# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_off', models.BooleanField(default=False)),
                ('sensors_off', models.IntegerField(blank=True, default=0)),
                ('device_sleep', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Device')),
            ],
        ),
    ]
