# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='device_sleep',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='sensors_off',
        ),
        migrations.AddField(
            model_name='configuration',
            name='device_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
