# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_auto_20160505_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='config_revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=8),
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
