# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20160505_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
