# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_auto_20160505_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='generating_logs',
            field=models.BooleanField(default=True),
        ),
    ]
