# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_device_generating_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='generating_logs',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
